MODELS_CATALOG = [
    {'id': 'deepseek/deepseek-v4-flash-0731', 'name': 'DeepSeek V4 Flash 0731', 'provider': 'RouterAI', 'description': 'DeepSeek V4 Flash 0731 — это модель с разреженной смесью экспертов от DeepSeek, с 13 миллиардами активных параметров из 284 миллиардов общих. Эта пересмотренная версия, прошедшая повторное обучение, подходит для кодирования, рассуждений и рабочих процессов агентов.', 'context_length': 131072, 'pricing': {'prompt': 20.4, 'completion': 12.0, 'prompt_formatted': '20.40', 'completion_formatted': '12.00'}, 'logo': 'https://upload.wikimedia.org/wikipedia/commons/1/13/ChatGPT-Logo.png'},
    {'id': 'qwen/qwen3.5-9b', 'name': 'Qwen3.5-9B', 'provider': 'RouterAI', 'description': 'Qwen3.5-9B — это мультимодальная базовая модель из семейства Qwen3.5, разработанная для обеспечения мощных возможностей в области рассуждений, программирования и визуального понимания в эффективной архитектуре с 9 миллиардами параметров. Она использует унифицированный дизайн для работы с визуальной и языковой информацией с ранним объединением мультимодальных токенов, что позволяет модели обрабатывать и анализировать текст и изображения в одном контексте.', 'context_length': 268288, 'pricing': {'prompt': 12.0, 'completion': 19.2, 'prompt_formatted': '12.00', 'completion_formatted': '19.20'}, 'logo': 'https://upload.wikimedia.org/wikipedia/commons/1/13/ChatGPT-Logo.png'},
    {'id': 'qwen/qwen3.5-flash-02-23', 'name': 'Qwen3.5-Flash', 'provider': 'RouterAI', 'description': 'Нативные модели Qwen3.5 vision-language Flash построены на гибридной архитектуре, которая интегрирует линейный механизм внимания с разреженной моделью смеси экспертов, достигая более высокой эффективности вывода. По сравнению с серией 3, эти модели обеспечивают значительный прорыв в производительности как для чисто текстовых, так и для мультимодальных задач, предлагая быстрое время отклика при сбалансированности скорости вывода и общей производительности.', 'context_length': 1048576, 'pricing': {'prompt': 7.2, 'completion': 32.4, 'prompt_formatted': '7.20', 'completion_formatted': '32.40'}, 'logo': 'https://upload.wikimedia.org/wikipedia/commons/1/13/ChatGPT-Logo.png'},
    {'id': 'z-ai/glm-4.7-flash', 'name': 'GLM 4.7 Flash', 'provider': 'RouterAI', 'description': 'Как модель класса 30B SOTA, GLM-4.7-Flash предлагает новый вариант, который балансирует между производительностью и эффективностью. Она дополнительно оптимизирована для агентного кодирования, укрепляя возможности кодирования, планирования задач на длительный срок и сотрудничества с инструментами, и достигла ведущих результатов среди моделей с открытым исходным кодом того же размера на нескольких актуальных публичных рейтингах.', 'context_length': 207872, 'pricing': {'prompt': 7.2, 'completion': 50.4, 'prompt_formatted': '7.20', 'completion_formatted': '50.40'}, 'logo': 'https://upload.wikimedia.org/wikipedia/commons/1/13/ChatGPT-Logo.png'},
    {'id': 'openai/gpt-oss-safeguard-20b', 'name': 'gpt-oss-safeguard-20b', 'provider': 'RouterAI', 'description': 'gpt-oss-safeguard-20b — это модель рассуждений по безопасности от OpenAI, построенная на основе gpt-oss-20b. Эта модель с открытыми весами и 21 миллиардом параметров, использующая архитектуру Mixture-of-Experts (MoE), обеспечивает более низкую задержку для задач безопасности, таких как классификация контента, фильтрация LLM и маркировка доверия и безопасности.', 'context_length': 134144, 'pricing': {'prompt': 9.6, 'completion': 38.4, 'prompt_formatted': '9.60', 'completion_formatted': '38.40'}, 'logo': 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg'},
    {'id': 'google/gemma-4-31b-it', 'name': 'Gemma 4 31B', 'provider': 'RouterAI', 'description': 'Gemma 4 31B Instruct — это плотная мультимодальная модель от Google DeepMind с 30,7 миллиардами параметров, поддерживающая текстовый и визуальный ввод с текстовым выводом. Обладает контекстным окном на 256 тысяч токенов, настраиваемым режимом мышления/рассуждения, возможностью нативного вызова функций и многоязычной поддержкой более чем на 140 языках. Сильна в задачах программирования, рассуждения и понимания документов. Лицензия Apache 2.0.', 'context_length': 268288, 'pricing': {'prompt': 9.6, 'completion': 44.4, 'prompt_formatted': '9.60', 'completion_formatted': '44.40'}, 'logo': 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Google_%22G%22_logo.svg'},
    {'id': 'openai/gpt-oss-120b', 'name': 'gpt-oss-120b', 'provider': 'RouterAI', 'description': 'gpt-oss-120b — это языковая модель с открытыми весами от OpenAI, состоящая из 117 миллиардов параметров и использующая архитектуру Mixture-of-Experts (MoE). Она предназначена для задач, требующих высокого уровня рассуждений, агентности и универсального применения. В каждом прямом проходе активируется 5,1 миллиарда параметров, и модель оптимизирована для работы на одном графическом процессоре H100 с использованием нативной квантования MXFP4. Модель поддерживает настраиваемую глубину рассуждений, полный доступ к цепочке рассуждений и нативное использование инструментов, включая вызов функций, просмотр и генерацию структурированного вывода.', 'context_length': 134144, 'pricing': {'prompt': 3.84, 'completion': 21.6, 'prompt_formatted': '3.84', 'completion_formatted': '21.60'}, 'logo': 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg'},
    {'id': 'openai/gpt-oss-20b', 'name': 'gpt-oss-20b', 'provider': 'RouterAI', 'description': 'gpt-oss-20b — это модель с открытыми весами на 21 миллиард параметров, выпущенная OpenAI под лицензией Apache 2.0. Она использует архитектуру Mixture-of-Experts (MoE) с 3,6 миллиардами активных параметров на каждый прямой проход, оптимизированную для инференса с низкой задержкой и развертывания на потребительском или однопроцессорном оборудовании. Модель обучена в формате ответов Harmony от OpenAI и поддерживает настройку уровня рассуждений, тонкую настройку и агентные возможности, включая вызов функций, использование инструментов и структурированные выводы.', 'context_length': 134144, 'pricing': {'prompt': 3.84, 'completion': 15.6, 'prompt_formatted': '3.84', 'completion_formatted': '15.60'}, 'logo': 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg'},
    {'id': 'google/gemini-2.5-flash-lite', 'name': 'Gemini 2.5 Flash Lite', 'provider': 'RouterAI', 'description': 'Gemini 2.5 Flash-Lite — это облегчённая модель рассуждений в семействе Gemini 2.5, оптимизированная для сверхнизкой задержки и экономической эффективности. Она обеспечивает улучшенную пропускную способность, более быстрое генерирование токенов и лучшую производительность по общим тестам по сравнению с более ранними моделями Flash. По умолчанию “мышление” (т.е. многократное рассуждение) отключено, чтобы приоритет отдавался скорости, но разработчики могут включить его через параметр Reasoning API, чтобы избирательно обменивать стоимость на интеллект.', 'context_length': 1048576, 'pricing': {'prompt': 12.0, 'completion': 50.4, 'prompt_formatted': '12.00', 'completion_formatted': '50.40'}, 'logo': 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Google_%22G%22_logo.svg'},
    {'id': 'openrouter/auto-beta', 'name': 'OpenRouter Auto Beta', 'provider': 'OpenRouter', 'description': 'OpenRouter Auto Beta.', 'context_length': 1048576, 'pricing': {'prompt': 12.0, 'completion': 12.0, 'prompt_formatted': '12.00', 'completion_formatted': '12.00'}, 'logo': 'https://upload.wikimedia.org/wikipedia/commons/1/13/ChatGPT-Logo.png'},
    {'id': 'deepseek/deepseek-v4-pro', 'name': 'DeepSeek V4 Pro', 'provider': 'DeepSeek', 'description': 'DeepSeek V4 Pro — это крупномасштабная модель Mixture-of-Experts от DeepSeek с общим количеством параметров 1,6 триллиона и 49 миллиардами активированных параметров, поддерживающая контекстное окно в 1 миллион токенов.', 'context_length': 1048576, 'pricing': {'prompt': 54.0, 'completion': 108.0, 'prompt_formatted': '54.00', 'completion_formatted': '108.00'}, 'logo': 'https://upload.wikimedia.org/wikipedia/commons/1/13/ChatGPT-Logo.png'},
]

AVAILABLE_PROVIDERS = [
    ('routerai', 'RouterAI', 'RouterAI Auto'),
    ('openrouter', 'OpenRouter', 'OpenRouter Auto Beta'),
    ('deepseek', 'DeepSeek', 'DeepSeek V4 Pro'),
]

