from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('room/create/', views.create_room, name='create_room'),
    path('room/<slug:slug>/', views.room_detail, name='room_detail'),
    path('room/<slug:slug>/delete/', views.delete_room, name='delete_room'),
    path('room/<slug:slug>/invite/', views.create_room_invite, name='create_room_invite'),
    path('room/<slug:slug>/ai-integrations/', views.manage_room_ai_integrations, name='manage_room_ai_integrations'),
    path('room/<slug:slug>/messages/', views.get_messages, name='get_messages'),
    path('room/<slug:slug>/send/', views.send_message, name='send_message'),
    path('room/<slug:slug>/start_game/', views.start_movie_game, name='start_movie_game'),
    path('profile/', views.profile, name='profile'),
    path('profile/add-integration/', views.add_ai_integration, name='add_ai_integration'),
    path('profile/subscribe/', views.create_yookassa_subscription, name='create_yookassa_subscription'),
    path('profile/confirm-subscription/', views.confirm_subscription, name='subscription_confirm'),
    path('profile/topup/', views.topup_balance, name='topup_balance'),
    path('payment/return/', views.payment_return, name='payment_return'),
    path('terms/', views.terms_view, name='terms'),
    path('privacy/', views.privacy_view, name='privacy'),
    path('contacts/', views.contacts_view, name='contacts'),
    path('message/<int:message_id>/react/', views.toggle_message_reaction, name='toggle_message_reaction'),
    path('room/<slug:slug>/stats/', views.room_stats, name='room_stats'),
    path('achievements/', views.achievements, name='achievements'),
    path('ai-management/', views.ai_management, name='ai_management'),
    path('ai-management/integration/<int:pk>/edit/', views.edit_ai_integration, name='edit_ai_integration'),
    path('ai-management/integration/<int:pk>/delete/', views.delete_ai_integration, name='delete_ai_integration'),
    path('ai-management/my-keys/', views.routerai_keys_view, name='routerai_keys'),
    path('ai-management/generate-key/', views.generate_routerai_key, name='generate_routerai_key'),
    path('ai-management/models/', views.models_pricing, name='models_pricing'),
    path('room/<slug:slug>/toggle-pin/', views.toggle_room_pin, name='toggle_room_pin'),
    path('image-chat/', views.image_generation_chat, name='image_generation_chat'),
    path('image-chat/generate/', views.generate_image, name='generate_image'),
    path('image-chat/history/', views.image_history, name='image_history'),
    path('image-chat/stats/', views.image_gen_stats, name='image_gen_stats'),
    path('image-chat/save-stat/', views.save_image_stat, name='save_image_stat'),
    path('ai-management/usage-chart/', views.ai_usage_chart, name='ai_usage_chart'),
    path('sitemap.xml', views.sitemap, name='sitemap'),
    path('robots.txt', views.robots_txt, name='robots_txt'),
    path('favicon.ico', views.favicon_view, name='favicon'),
    path('media/<path:path>', views.media_serve_view, name='media_serve'),
]


