# Generated by Django 4.2.30 on 2026-07-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_roomaiintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiintegration',
            name='provider',
            field=models.CharField(choices=[('gpt', 'ChatGPT'), ('groq', 'Groq'), ('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('claude', 'Claude')], max_length=30),
        ),
        migrations.AlterField(
            model_name='roomaiintegration',
            name='provider',
            field=models.CharField(choices=[('gpt', 'ChatGPT'), ('groq', 'Groq'), ('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('claude', 'Claude')], max_length=30),
        ),
    ]
