# Generated by Django 4.2.30 on 2026-07-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_add_cerebras_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_prompt',
            field=models.TextField(blank=True, help_text='Дополнительные правила для нейросети в чате.'),
        ),
    ]
