# Generated by Django 4.2.30 on 2026-07-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_add_custom_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiintegration',
            name='model_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
