# Generated by Django 4.2.30 on 2026-08-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_achievement_useractivity_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='lottie_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='lottie-celebration', max_length=50),
        ),
    ]
