# Generated by Django 4.2.30 on 2026-08-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_achievement_lottie_url_alter_achievement_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned Room'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='showcase_achievements',
            field=models.ManyToManyField(blank=True, related_name='showcased_by', to='chat.achievement'),
        ),
    ]
