# Generated by Django 4.2.30 on 2026-08-03 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_room_is_pinned_userprofile_showcase_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='showcase_achievements',
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gpt', 'ChatGPT'), ('groq', 'Groq'), ('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('claude', 'Claude'), ('cerebras', 'Cerebras')], max_length=30)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='chat.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
