# Generated by Django 4.2.30 on 2026-08-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_generatedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='image_url',
            field=models.TextField(),
        ),
    ]
