# Generated by Django 4.2.30 on 2026-08-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_message_image_message_message_type_message_voice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='response_time',
            field=models.FloatField(default=0.0, help_text='Время ответа в секундах'),
        ),
    ]
