# Generated by Django 4.2.30 on 2026-08-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_add_response_time_to_aiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='generation_time',
            field=models.FloatField(blank=True, help_text='Время генерации в секундах', null=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
