# Generated by Django 4.2.30 on 2026-08-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_add_generation_fields_to_generatedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('general', 'Общее'), ('technology', 'Технологии'), ('ai', 'ИИ'), ('programming', 'Программирование'), ('study', 'Учёба'), ('science', 'Наука'), ('books', 'Книги'), ('anime', 'Аниме'), ('sport', 'Спорт'), ('news', 'Новости'), ('humor', 'Юмор'), ('creative', 'Творчество'), ('design', 'Дизайн'), ('business', 'Бизнес'), ('startups', 'Стартапы'), ('travel', 'Путешествия'), ('languages', 'Языки'), ('games', 'Игры'), ('movies', 'Фильмы'), ('music', 'Музыка'), ('social', 'Общение')], default='general', max_length=30),
        ),
    ]
