# Generated by Django 4.2.30 on 2026-08-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_update_room_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiintegration',
            name='provider',
            field=models.CharField(choices=[('cloro', 'Cloro'), ('gpt', 'ChatGPT'), ('groq', 'Groq'), ('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('claude', 'Claude'), ('cerebras', 'Cerebras')], max_length=30),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='provider',
            field=models.CharField(choices=[('cloro', 'Cloro'), ('gpt', 'ChatGPT'), ('groq', 'Groq'), ('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('claude', 'Claude'), ('cerebras', 'Cerebras')], max_length=30),
        ),
        migrations.AlterField(
            model_name='roomaiintegration',
            name='provider',
            field=models.CharField(choices=[('cloro', 'Cloro'), ('gpt', 'ChatGPT'), ('groq', 'Groq'), ('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('claude', 'Claude'), ('cerebras', 'Cerebras')], max_length=30),
        ),
    ]
