# Generated by Django 4.2.30 on 2026-08-05 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0020_alter_aiintegration_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True, verbose_name='Ключ сессии')),
                ('guest_name', models.CharField(max_length=100, verbose_name='Имя гостя')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('messages_count', models.IntegerField(default=0, verbose_name='Отправлено сообщений')),
                ('images_count', models.IntegerField(default=0, verbose_name='Сгенерировано фото')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Первый визит')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Незарегистрированный пользователь',
                'verbose_name_plural': 'Незарегистрированные пользователи',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_images', to='chat.guestsession'),
        ),
        migrations.AddField(
            model_name='message',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.guestsession'),
        ),
    ]
