# Generated by Django 4.2.30 on 2026-08-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_guestsession_message_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiintegration',
            name='custom_prompt',
            field=models.TextField(blank=True, help_text='Инструкции и роль для этой модели в чате', verbose_name='Персональный промпт'),
        ),
    ]
