# Generated by Django 4.2.30 on 2026-08-06 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0022_aiintegration_custom_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiintegration',
            name='provider',
            field=models.CharField(choices=[('cloro', 'Cloro'), ('gpt', 'ChatGPT'), ('groq', 'Groq'), ('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('claude', 'Claude'), ('cerebras', 'Cerebras'), ('openrouter', 'OpenRouter')], max_length=30),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='provider',
            field=models.CharField(choices=[('cloro', 'Cloro'), ('gpt', 'ChatGPT'), ('groq', 'Groq'), ('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('claude', 'Claude'), ('cerebras', 'Cerebras'), ('openrouter', 'OpenRouter')], max_length=30),
        ),
        migrations.AlterField(
            model_name='roomaiintegration',
            name='provider',
            field=models.CharField(choices=[('cloro', 'Cloro'), ('gpt', 'ChatGPT'), ('groq', 'Groq'), ('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('claude', 'Claude'), ('cerebras', 'Cerebras'), ('openrouter', 'OpenRouter')], max_length=30),
        ),
        migrations.CreateModel(
            name='MovieGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('movie_name', models.CharField(max_length=255)),
                ('hints', models.JSONField(default=list)),
                ('current_hint_index', models.IntegerField(default=0)),
                ('attempts_since_last_hint', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_games', to='chat.room')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
