# Generated by Django 4.2.30 on 2026-08-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_alter_aiintegration_provider_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='aiintegration',
            options={'verbose_name': 'AI Интеграция', 'verbose_name_plural': 'AI Интеграции'},
        ),
        migrations.AlterModelOptions(
            name='aiusagelog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог использования AI', 'verbose_name_plural': 'Логи использования AI'},
        ),
        migrations.AlterModelOptions(
            name='generatedimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сгенерированное изображение', 'verbose_name_plural': 'Сгенерированные изображения'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelOptions(
            name='roominvitation',
            options={'verbose_name': 'Приглашение в комнату', 'verbose_name_plural': 'Приглашения в комнаты'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'verbose_name': 'Достижение пользователя', 'verbose_name_plural': 'Достижения пользователей'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-date'], 'verbose_name': 'Активность пользователя', 'verbose_name_plural': 'Активность пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='Является ли пользователь системным ботом', verbose_name='Бот'),
        ),
    ]
