# Generated by Django 4.2.30 on 2026-08-10 12:18

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_alter_message_image_alter_message_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='streak_checked_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_messages_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Messages'),
        ),
        migrations.AlterField(
            model_name='aiintegration',
            name='api_key',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
