# Generated by Django 4.2.30 on 2026-08-13 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0027_userprofile_balance_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiintegration',
            name='provider',
            field=models.CharField(choices=[('routerai', 'RouterAI'), ('cloro', 'Cloro'), ('gpt', 'ChatGPT'), ('groq', 'Groq'), ('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('claude', 'Claude'), ('cerebras', 'Cerebras'), ('openrouter', 'OpenRouter')], max_length=30),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='provider',
            field=models.CharField(choices=[('routerai', 'RouterAI'), ('cloro', 'Cloro'), ('gpt', 'ChatGPT'), ('groq', 'Groq'), ('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('claude', 'Claude'), ('cerebras', 'Cerebras'), ('openrouter', 'OpenRouter')], max_length=30),
        ),
        migrations.AlterField(
            model_name='roomaiintegration',
            name='provider',
            field=models.CharField(choices=[('routerai', 'RouterAI'), ('cloro', 'Cloro'), ('gpt', 'ChatGPT'), ('groq', 'Groq'), ('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('claude', 'Claude'), ('cerebras', 'Cerebras'), ('openrouter', 'OpenRouter')], max_length=30),
        ),
        migrations.CreateModel(
            name='RouterAIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название ключа')),
                ('key_hash', models.CharField(max_length=150, unique=True, verbose_name='Hash ключа')),
                ('key_value', models.CharField(max_length=255, verbose_name='Значение ключа')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Отключен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routerai_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Ключ RouterAI',
                'verbose_name_plural': 'API Ключи RouterAI',
                'ordering': ['-created_at'],
            },
        ),
    ]
