# Generated by Django 4.2.30 on 2026-08-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_alter_aiintegration_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на аватарку'),
        ),
    ]
