# Generated by Django 4.2.30 on 2026-08-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiintegration',
            name='auto_reply',
            field=models.BooleanField(default=False, help_text='Модель будет отвечать на каждое сообщение в комнате без обращения @', verbose_name='Отвечать на все сообщения'),
        ),
        migrations.AddField(
            model_name='aiintegration',
            name='nickname',
            field=models.CharField(blank=True, help_text='Альтернативное имя для обращения в чате через @ник', max_length=50, verbose_name='Ник модели'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message', verbose_name='Ответ на сообщение'),
        ),
    ]
