# Generated by Django 4.2.30 on 2026-08-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_aiintegration_nickname_autoreply_message_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='guestsession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice')], db_index=True, default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('general', 'Общее'), ('technology', 'Технологии'), ('ai', 'ИИ'), ('programming', 'Программирование'), ('study', 'Учёба'), ('science', 'Наука'), ('books', 'Книги'), ('anime', 'Аниме'), ('sport', 'Спорт'), ('news', 'Новости'), ('humor', 'Юмор'), ('creative', 'Творчество'), ('design', 'Дизайн'), ('business', 'Бизнес'), ('startups', 'Стартапы'), ('travel', 'Путешествия'), ('languages', 'Языки'), ('games', 'Игры'), ('movies', 'Фильмы'), ('music', 'Музыка'), ('social', 'Общение')], db_index=True, default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pinned Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Private Room'),
        ),
        migrations.AlterField(
            model_name='routeraikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
