# Generated by Django 4.2.30 on 2026-08-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_alter_aiusagelog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на аватарку'),
        ),
    ]
