# Generated by Django 4.2.30 on 2026-08-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_alter_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'id'], name='chat_message_room_id_idx'),
        ),
    ]
