"""
Django settings for nextroom_project project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from django.core.exceptions import ImproperlyConfigured

import os
import urllib.parse
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

if not os.environ.get('VERCEL') and not os.environ.get('DJANGO_DEBUG', 'False') == 'True' and not SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY must not be empty in production!")
elif not SECRET_KEY:
    SECRET_KEY = 'django-insecure-4oy4*jok7@v$c(#d=w8&pj+v90imq(v4zu*5u+wv40)@qwc4=n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'
if os.environ.get('VERCEL'):
    DEBUG = False

# Security Settings
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
DATA_UPLOAD_MAX_MEMORY_SIZE = 20971520  # 20 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 20971520  # 20 MB

if not DEBUG:
    # Принудительно перенаправлять все HTTP запросы на HTTPS
    SECURE_SSL_REDIRECT = True
    
    # Включаем HSTS, чтобы браузеры запомнили, что сайт работает только по HTTPS (на 1 год)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

env_hosts = os.environ.get('ALLOWED_HOSTS')
ALLOWED_HOSTS = env_hosts.split(',') if env_hosts else []
# Always allow vercel subdomains in this environment to prevent DisallowedHost on deployments
ALLOWED_HOSTS.append('.vercel.app')
ALLOWED_HOSTS.append('nextroom.vercel.app')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'nextroom_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nextroom_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


DATABASE_URL = os.environ.get('DATABASE_URL') or os.environ.get('DATABASE_URL_UNPOOLED') or os.environ.get('DATABASE_URL_DATABASE_URL')
if DATABASE_URL:
    url = urllib.parse.urlparse(DATABASE_URL)
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': url.path[1:],
        'USER': url.username,
        'PASSWORD': url.password,
        'HOST': url.hostname,
        'PORT': url.port or '5432',
        'CONN_MAX_AGE': 600,
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
elif not (BASE_DIR / 'db.sqlite3').exists() and os.environ.get('VERCEL'):
    raise ImproperlyConfigured(
        'DATABASE_URL is not configured. Set DATABASE_URL to your Neon/PostgreSQL database URL in Vercel environment variables.'
    )


# Cache Configuration (Supports Redis from Upstash/Cloud with fail-safe fallback)
REDIS_URL = os.environ.get('REDIS_URL') or os.environ.get('KV_URL') or os.environ.get('UPSTASH_REDIS_URL') or os.environ.get('STORAGE_REDIS_URL')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': True,
                'SOCKET_CONNECT_TIMEOUT': 2,
                'SOCKET_TIMEOUT': 2,
            }
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'nextroom-cache',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'


TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
WHITENOISE_MANIFEST_STRICT = False

MEDIA_URL = '/media/'

# Yandex Cloud Object Storage / S3 Configuration
_s3_key = (
    os.environ.get('AWS_ACCESS_KEY_ID')
    or os.environ.get('YC_ACCESS_KEY_ID')
    or os.environ.get('YANDEX_ACCESS_KEY_ID')
    or os.environ.get('S3_KEY_ID')
)
_s3_secret = (
    os.environ.get('AWS_SECRET_ACCESS_KEY')
    or os.environ.get('YC_SECRET_ACCESS_KEY')
    or os.environ.get('YANDEX_SECRET_ACCESS_KEY')
    or os.environ.get('S3_SECRET_KEY')
)
_s3_bucket = (
    os.environ.get('AWS_STORAGE_BUCKET_NAME')
    or os.environ.get('YC_BUCKET_NAME')
    or os.environ.get('YANDEX_STORAGE_BUCKET_NAME')
    or os.environ.get('S3_BUCKET_NAME')
)

if _s3_key and _s3_secret and _s3_bucket:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_ACCESS_KEY_ID = _s3_key
    AWS_SECRET_ACCESS_KEY = _s3_secret
    AWS_STORAGE_BUCKET_NAME = _s3_bucket
    AWS_S3_ENDPOINT_URL = (
        os.environ.get('AWS_S3_ENDPOINT_URL')
        or os.environ.get('YC_ENDPOINT_URL')
        or 'https://storage.yandexcloud.net'
    )
    AWS_S3_REGION_NAME = (
        os.environ.get('AWS_S3_REGION_NAME')
        or os.environ.get('YC_REGION_NAME')
        or 'ru-central1'
    )
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=31536000, public',
    }
    if os.environ.get('AWS_S3_CUSTOM_DOMAIN'):
        AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN')
elif os.environ.get('VERCEL') or not os.access(BASE_DIR, os.W_OK):
    MEDIA_ROOT = Path('/tmp') / 'media'
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'landing'
SOCIAL_AUTH_LOGIN_ERROR_URL = 'landing'

SOCIAL_AUTH_GITHUB_KEY = os.environ.get('SOCIAL_AUTH_GITHUB_KEY')
SOCIAL_AUTH_GITHUB_SECRET = os.environ.get('SOCIAL_AUTH_GITHUB_SECRET')

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'landing'
LOGIN_URL = 'login'

# Groq AI gateway settings
GROQ_API_URL = os.environ.get('GROQ_API_URL', 'https://api.groq.com/openai/v1')

# Cerebras AI gateway settings
CEREBRAS_API_KEY = os.environ.get('CEREBRAS_API_KEY', '')

# Yookassa payment gateway settings
YOOKASSA_SHOP_ID = os.environ.get('YOOKASSA_SHOP_ID')
YOOKASSA_SECRET_KEY = os.environ.get('YOOKASSA_SECRET_KEY')

